*** N-dimension and Reshape ***

In [0]:
import numpy as np

In [2]:
c = np.array([[0,1,2],[3,4,5]])
print(c, len(c),len(c[0]), c.shape, type(c))

[[0 1 2]
 [3 4 5]] 2 3 (2, 3) <class 'numpy.ndarray'>


In [10]:
c1 = np.array([[0,1,2],[3,4],[]])
c1.shape

(3,)

**Reshape**

In [29]:
aa = np.arange(12)
aa, aa.shape, type(aa)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,), numpy.ndarray)

In [30]:
bb = aa.reshape(3,4)
bb, bb.shape, type(bb)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), (3, 4), numpy.ndarray)

**Transpose**

In [12]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [14]:
a1 = np.array([[1,2,3],[4,5,6],[1,2,3],[4,5,6]])
a1.T

array([[1, 4, 1, 4],
       [2, 5, 2, 5],
       [3, 6, 3, 6]])

*** Indexing & Slicing ***

In [16]:
b = np.array([[0,1,2],[3,4,5]])
print(b, b[0][0],b[0,0],b[0,1],b[0][1],b[-1,-1])

[[0 1 2]
 [3 4 5]] 0 0 1 1 5


In [15]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]      #Indexing
x, x.shape, y, y.shape
# y는 인덱싱으로 추출되어 1차원이 만들어짐

(array([[1, 2],
        [3, 4],
        [5, 6]]), (3, 2), array([1, 4, 5]), (3,))

In [23]:
y2 = x[1:3,[0,1]]     #Slicing
y2, y2.shape
# y2는 슬라이싱으로 추출되어 다차원으로 만들어짐

(array([[3, 4],
        [5, 6]]), (2, 2))

**(+)마스크를 씌워서 연산하기**

In [27]:
a2 = np.array([0,1,2,3,4,5,6,7,8,9])
idx = np.array([True,False,True,False,True,False,True,False,True,False,])
print(a2[idx], a2[a2%2==0],a2%2==0)
# a2%2==0 은 a2라는 배열에 2가 Broadcasting 되어 각각 같은 값의 연산을 매칭해줌

[0 2 4 6 8] [0 2 4 6 8] [ True False  True False  True False  True False  True False]


**(+)np.nan, np.isnan**

In [28]:
x1 = np.array([[0,1,2],[np.nan,4,5],[6,7,8],[9,10,11]])
x1, x1[x1>5],x1[np.isnan(x1)]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


(array([[ 0.,  1.,  2.],
        [nan,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]), array([ 6.,  7.,  8.,  9., 10., 11.]), array([nan]))

*** 매트릭스 간의 연산 ***

매트릭스 간의 연산을 위한 조건\
"앞 매트릭스의 열 개수 == 뒤 매트릭스의 행 개수"

In [36]:
#기본
a3 = np.array([[0,1,2,3],[4,5,6,7]])
a3, a3[0],a3[0,:],a3[:2,:2]

(array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([0, 1, 2, 3]),
 array([0, 1, 2, 3]),
 array([[0, 1],
        [4, 5]]))

In [38]:
print(a3[0].shape,a3[0,:].shape)

(4,) (4,)


In [32]:
c2 = np.array([[0,1,2],[3,4,5]])
print(c2, len(c2), c2.shape, type(c2), c2.itemsize)

[[0 1 2]
 [3 4 5]] 2 (2, 3) <class 'numpy.ndarray'> 8


In [33]:
d = np.array([2,3,4])
print(d, len(d), d.shape, type(d))

[2 3 4] 3 (3,) <class 'numpy.ndarray'>


In [34]:
c2 + d

array([[2, 4, 6],
       [5, 7, 9]])

### 통계

In [39]:
x2 = np.array([1,2,3,1])
np.sum(x2), np.max(x2),np.mean(x2),np.median(x2),np.std(x2)

(7, 3, 1.75, 1.5, 0.82915619758885)

In [40]:
x3 = np.array([[0,1,2],[7,8,9],[2,3,4],[4,5,6]])
np.sum(x3), np.max(x3),np.mean(x3),np.median(x3),np.std(x3)

(51, 9, 4.25, 4.0, 2.7118566825454966)

In [41]:
x4 = np.array([[1,3,5,7],[2,4,6,8]])
x4.ndim, x4.shape, len(x4), x4[0], x4[:,3]

(2, (2, 4), 2, array([1, 3, 5, 7]), array([7, 8]))

*** Axis ***\
axis = 0 (디폴트값) : 행 / axis = 1 : 열


In [43]:
np.sum(x4,axis=0), np.sum(x4,axis=1), np.sum(x4[0]),np.sum(x4[:,3])

(array([ 3,  7, 11, 15]), array([16, 20]), 16, 15)

In [45]:
d1 = np.array([[[1,3,5],[5,6,7]],[[5,6,7],[5,6,7]]])
d1, d1.dtype, type(d1), d1.ndim,d1.shape,len(d1),np.sum(d1,axis=2)

(array([[[1, 3, 5],
         [5, 6, 7]],
 
        [[5, 6, 7],
         [5, 6, 7]]]),
 dtype('int64'),
 numpy.ndarray,
 3,
 (2, 2, 3),
 2,
 array([[ 9, 18],
        [18, 18]]))

### Try - Ndarray

In [0]:
#{'num':'1', 'kor':90,'eng':80,'math':85,'total':0,'avg':0.0,'min':80,'max':90}
students_score = [
                  [1,90,80,85,0,0.0,0,0],
                  [2,88,85,90,0,0.0,0,0],
                  [3,32,85,90,0,0.0,0,0],
                  [4,42,75,93,0,0.0,0,0],
                  [5,82,86,88,0,0.0,0,0]
]

In [53]:
# 각 구성원 total, avg 필드 각 생성 및 값 구하기
#total
ndarray = np.array(students_score)
ndarray[:,4] = np.sum(ndarray[:,1:4],axis=1)
ndarray

array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
       [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
       [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
       [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
       [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]])

array([[  1.,  90.,  80.,  85., 255.,   0.,   0.,   0.],
       [  2.,  88.,  85.,  90., 263.,   0.,   0.,   0.],
       [  3.,  32.,  85.,  90., 207.,   0.,   0.,   0.],
       [  4.,  42.,  75.,  93., 210.,   0.,   0.,   0.],
       [  5.,  82.,  86.,  88., 256.,   0.,   0.,   0.]])

In [0]:
#학급 평균 구하기
class_avg = np.mean()