#Manipulation

## concatenate

In [0]:
import numpy as np

In [0]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.concatenate((a,b)))
print(np.concatenate((a,b),axis=0))
print(np.concatenate((a,b),axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [0]:
a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8],[9,10]])
print(np.concatenate((a1,b1)))
print(np.concatenate((a1,b1),axis=0))
print(np.concatenate((a1,b1),axis=1))

#Error 이유 : 매트릭스는 박스가 만들어져야 하는데, 형태(차원)이 맞지 않으면 만들 수 없음

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


ValueError: ignored

##split

In [0]:
a2 = np.arange(9)
b2 = np.split(a2,3)

a2, type(a2), b2, type(b2)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 numpy.ndarray,
 [array([0, 1, 2, 3, 4, 5, 6, 7, 8])],
 list)

##resize

In [0]:
a3 = np.array([[1,2,3],[4,5,6]])
resz = np.resize(a3,(3,2))
resz, resz.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]), (3, 2))

##insert

In [30]:
a4 = np.array([[1,2],[3,4],[5,6]])
np.insert(a4, 1,[11,12],axis=0), np.insert(a4,2,11,axis=1)
print(a4)

[[1 2]
 [3 4]
 [5 6]]


##delete

In [0]:
a5 = np.arange(12).reshape(3,4)
print(a5)
print(np.delete(a5,5))      #인덱스의 값을 삭제
print(np.delete(a5,1,axis=1))     #인덱스 열을 삭제 (axis=0 : 인덱스 행을 삭제)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  6  7  8  9 10 11]
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [0]:
#test
test_a5 = np.array(['a','b','c','d','e','f','g','h','i','j','k','l']).reshape(3,4)
print(test_a5)
print(np.delete(test_a5,5))
print(np.delete(test_a5,1,axis=0))

[['a' 'b' 'c' 'd']
 ['e' 'f' 'g' 'h']
 ['i' 'j' 'k' 'l']]
['a' 'b' 'c' 'd' 'e' 'g' 'h' 'i' 'j' 'k' 'l']
[['a' 'b' 'c' 'd']
 ['i' 'j' 'k' 'l']]
