In [5]:
a = np.array([[1,2,3],[1,0,-1],[4,5,6]])
b = np.array([[-1,1],[3,2],[-2,5]])
a * b

ValueError: ignored

Sample

In [1]:
import numpy as np

student_score = [
 [1, 90, 80, 85, 0, 0.0, 0, 0],
 [2, 88, 85, 90, 0, 0.0, 0, 0],
 [3, 32, 85, 90, 0, 0.0, 0, 0],
 [4, 42, 75, 93, 0, 0.0, 0, 0],
 [5, 82, 86, 88, 0, 0.0, 0, 0]
]
ndarray = np.array(student_score)
ndarray, type(ndarray), type(ndarray[0])

(array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
        [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
        [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
        [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
        [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]]),
 numpy.ndarray,
 numpy.ndarray)

In [2]:
#ndarray는 큐빅으로 자른다 (군집/묶음으로 자를 수 있다)
#python에서 리스트/딕셔너리는 슬라이싱이 가능하지만, 열/행 단위로만 가능 != 큐빅, 군집, 묶음

ndarray[:,0], ndarray[4,:], ndarray[2:4,1:4]

(array([1., 2., 3., 4., 5.]),
 array([ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]),
 array([[32., 85., 90.],
        [42., 75., 93.]]))

In [3]:
np.max(ndarray[:,0],axis = 0), np.sum(ndarray[:,1:4],axis=1)

(5.0, array([255., 263., 207., 210., 256.]))

In [14]:
ndarray[:,4] = np.sum(ndarray[:,1:4],axis=1)
ndarray, ndarray.shape

(array([[  1.,  90.,  80.,  85., 255.,   0.,   0.,   0.],
        [  2.,  88.,  85.,  90., 263.,   0.,   0.,   0.],
        [  3.,  32.,  85.,  90., 207.,   0.,   0.,   0.],
        [  4.,  42.,  75.,  93., 210.,   0.,   0.,   0.],
        [  5.,  82.,  86.,  88., 256.,   0.,   0.,   0.]]), (5, 8))

Broadcasting

In [8]:
x = np.array([[0,1,2],[1,2,3],[2,3,4],[4,5,6]])
x, x.shape, x.ndim

(array([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]), (4, 3), 2)

In [9]:
x + 0.4

array([[0.4, 1.4, 2.4],
       [1.4, 2.4, 3.4],
       [2.4, 3.4, 4.4],
       [4.4, 5.4, 6.4]])

In [12]:
x * [0,1,0.1]

array([[0. , 1. , 0.2],
       [0. , 2. , 0.3],
       [0. , 3. , 0.4],
       [0. , 5. , 0.6]])

조건연산(True,Fralse)

In [7]:
#스칼라배처럼 0과 어레이의 값 비교
(ndarray == 0), (ndarray[:,1:5]>20),  (ndarray[:,1:5]>20)&(ndarray[:,1:5]>80)      

(array([[False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True]]),
 array([[ True,  True,  True, False],
        [ True,  True,  True, False],
        [ True,  True,  True, False],
        [ True,  True,  True, False],
        [ True,  True,  True, False]]),
 array([[ True, False,  True, False],
        [ True,  True,  True, False],
        [False,  True,  True, False],
        [False, False,  True, False],
        [ True,  True,  True, False]]))

Mask

배열[(배열) & 조건]

In [17]:
#실제값에 마스킹을 해서 True인 값만 반환 -> 기존 배열과 크기가 맞지 않으므로 1차원으로 나옴
#실제값과 마스크하는 매트릭스(브라켓 안쪽 배열)의 크기를 맞춰줘야함
#마스크를 넣을 때 T/F (컨디션 like if문처럼) 모양으로 들어가는 것이 좋음

print (ndarray[(ndarray == 0)])
print(len(ndarray[(ndarray == 0)]))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
15


In [18]:
ndarr = ndarray[:,1:5]
ndarr[(ndarr > 20)]

array([ 90.,  80.,  85., 255.,  88.,  85.,  90., 263.,  32.,  85.,  90.,
       207.,  42.,  75.,  93., 210.,  82.,  86.,  88., 256.])

insert & delete

원본, 위치, 대상, 방향이 필요함

(파이썬은 1차원 수준으로 insert&delete 하기 때문에 방향성을 넣지 않아도 됨)

In [19]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])
np.insert(a,1,[11,12,13],axis = 0), np.insert(a,2,11,axis = 1)

(array([[ 1,  2,  3],
        [11, 12, 13],
        [ 3,  4,  5],
        [ 5,  6,  7]]), array([[ 1,  2, 11,  3],
        [ 3,  4, 11,  5],
        [ 5,  6, 11,  7]]))